pipeline {
    agent any
    parameters {
        booleanParam(defaultValue: false, description: "Deploy the App", name: "DEPLOY")
    }
    stages {
        stage('Test') {
            steps { 
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Package') {
            steps {
                sh "docker build -t myapp:latest --tag michaeljacinto/samplejava:myapp ."
            }
        }
        stage('Deliver') {
            when {
                expression { params.DEPLOY }
            }
            steps {
                sh "docker run myapp:latest"
            }
        }
    }
}